# Generated by Django 4.0.3 on 2022-03-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityProject', '0004_blockchain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='topic',
        ),
        migrations.AddField(
            model_name='blockchain',
            name='cryptocurrency',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
