# Generated by Django 4.0.3 on 2022-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityProject', '0005_remove_blockchain_topic_blockchain_cryptocurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='image',
            field=models.ImageField(default='avatar.svg', null=True, upload_to=''),
        ),
    ]
