# Generated by Django 4.0.2 on 2022-04-03 16:48

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityProject', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
