# Generated by Django 4.0.3 on 2022-04-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityProject', '0009_stocks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
