# Generated by Django 4.0.3 on 2022-04-05 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityProject', '0011_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
