# Generated by Django 4.0.3 on 2022-04-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityProject', '0012_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=256, null=True)),
                ('stock', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
