# Generated by Django 4.0.3 on 2022-04-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityProject', '0014_blockchain_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencystock',
            name='timeframe',
            field=models.TimeField(null=True),
        ),
    ]
