# Generated by Django 4.0.3 on 2022-04-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityProject', '0015_currencystock_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockchain',
            name='timeframe',
            field=models.TimeField(null=True),
        ),
    ]
