# Generated by Django 4.0.3 on 2022-04-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityProject', '0016_blockchain_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencystock',
            name='timeframe',
            field=models.DateTimeField(null=True),
        ),
    ]
