# Generated by Django 4.0.3 on 2022-04-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityProject', '0017_alter_currencystock_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencystock',
            name='timecheck',
            field=models.DateTimeField(null=True),
        ),
    ]
