# Generated by Django 4.0.3 on 2022-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UniversityProject', '0018_currencystock_timecheck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencystock',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='currencystock',
            name='timecheck',
        ),
        migrations.RemoveField(
            model_name='currencystock',
            name='timeframe',
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='timeframe',
            field=models.DateTimeField(null=True),
        ),
    ]
